# Generated by Django 5.1.3 on 2025-05-16 09:36

import appmustafa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmustafa', '0003_alter_animal_imagen_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='contenido',
            field=models.FileField(upload_to=appmustafa.models.pdf_upload_path, validators=[appmustafa.models.validate_pdf]),
        ),
    ]
