# Generated by Django 5.1.3 on 2025-06-14 18:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmustafa', '0004_alter_adopcion_contenido_alter_animal_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='pexels-leonardo-de-oliveira-872270-1770918_yp2wtl', max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(default='default_wtx8r7', max_length=255, verbose_name='foto_perfil'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='pexels-bekka419-804475_gpv7j8', max_length=255, verbose_name='imagen'),
        ),
    ]
