# Generated by Django 5.1.3 on 2025-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmustafa', '0004_alter_adopcion_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='aceptada',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10),
        ),
    ]
