# Generated by Django 5.1.3 on 2025-06-14 18:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmustafa', '0005_alter_animal_imagen_alter_customuser_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(default='default_as1n2l', max_length=255, verbose_name='foto_perfil'),
        ),
    ]
