# Generated by Django 5.1.3 on 2025-06-14 19:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmustafa', '0006_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(default='default_wtx8r7', max_length=255, verbose_name='foto_perfil'),
        ),
    ]
